services:
  - type: web
    name: homedetail
    runtime: python
    buildCommand: "./build.sh"
    startCommand: "gunicorn homedetail.wsgi:application"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: homedetail-db
          property: connectionString
      - key: SECRET_KEY
        generateValue: true
      - key: WEB_CONCURRENCY
        value: 4
      - key: DEBUG
        value: false
      - key: ALLOWED_HOSTS
        value: homedetail.onrender.com,localhost,127.0.0.1

databases:
  - name: homedetail-db
    databaseName: homedetail
    user: homedetail_user
    plan: free