services:
  - type: web
    name: homedetail
    runtime: python
    region: ohio  # o virginia/singapore según tu ubicación
    plan: free
    branch: main
    buildCommand: "./build.sh"
    startCommand: "gunicorn homedetail.wsgi:application --bind 0.0.0.0:$PORT"
    healthCheckPath: /
    autoDeploy: true
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0
      - key: SECRET_KEY
        generateValue: true
      - key: DEBUG
        value: false
      - key: ALLOWED_HOSTS
        sync: false
        value: .onrender.com
      - key: DISABLE_COLLECTSTATIC
        value: 0
      - key: RENDER_EXTERNAL_HOSTNAME
        fromService:
          type: web
          name: homedetail
          property: hostname
      - key: DATABASE_URL
        fromDatabase:
          name: homedetail-db
          property: connectionString

databases:
  - name: homedetail-db
    region: ohio
    plan: free
    databaseName: homedetail
    user: homedetail_user
    ipAllowList: []